### ISSUE TITLE
No Logger level configuration available for Winston

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/central-services-shared#8]
Log level configuration should be added to https://github.com/mojaloop/central-services-shared/blob/master/src/logger.js

Needs to provide a function to be able to set the method, or include it as a param for function Logger()

**Comment by igncp** [comment]
Hi, I was wondering if this issue is still valid. I can see that the level can be set via environment variable. Additionally, Winston allows setting the logger level after creation:

- https://github.com/winstonjs/winston/blob/e1e71884aab84ccb2131ca9400898eacbeb62fc9/README.md#using-logging-levels

```
logger.transports.console.level = 'debug';
logger.setLevels('debug'); // for the instance
```

I could reference this link in the repo README file, or maybe I misunderstood the issue. Thanks.

**Comment by lewisdaly** [comment]
Closing as outdated
